# DefSubstring

[[english.command]]
name = "DefSubstring"
args = ["a", "b"]
body = '
A string $#1$ is a substring of a string $#2$ if $#1$ can be obtained from $#2$ by the deletion of several (possibly, zero or all) characters from the beginning and several (possibly, zero or all) characters from the end.
'

[[russian.command]]
name = "DefSubstring"
args = ["a", "b"]
body = '
Строка $#1$ является подстрокой $#2$, если $#1$ может быть получена из $#2$ удалением нескольких (возможно, ни одного или всех) символов из начала и нескольких (возможно, ни одного или всех) символов из конца.
'

# DefPermutation

[[english.command]]
name = "DefPermutation"
args = ["n"]
body = '
A permutation of length $#1$ is an array consisting of $#1$ distinct integers from $1$ to $#1$ in arbitrary order. For example, $[2,3,1,5,4]$ is a permutation, but $[1,2,2]$ is not a permutation ($2$ appears twice in the array), and $[1,3,4]$ is also not a permutation ($#1=3$ but there is $4$ in the array).
'

[[russian.command]]
name = "DefPermutation"
args = ["n"]
body = '
Перестановкой длины $#1$ является массив, состоящий из $#1$ различных целых чисел от $1$ до $#1$ в произвольном порядке. Например, $[2,3,1,5,4]$ "--- перестановка, но $[1,2,2]$ не перестановка ($2$ встречается в массиве дважды) и $[1,3,4]$ тоже не перестановка ($#1=3$, но в массиве встречается $4$).
'

# Common

[[common.command]]
name = "DefTriangleNumber"
args = [""]
body = '
\frac{#1\cdot(#1-1)}{2}
'
